#!/bin/sh
#
# ufetch-arch - tiny system info for arch

## INFO

# user is already defined
host="      i-use-arch-btw"
os='Arch Linux'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='de'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='wm'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='wm'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${blue}"		# labels
nc="${reset}${bold}${blue}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${bold}${blue}"		# first color
c1="${reset}${blue}"			# second color

## OUTPUT

cat <<EOF

${c0}        /\        ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}       /^^\       ${lc}os:        ${ic}${os}${reset}
${c0}      /\   \      ${lc}kernel:    ${ic}${kernel}${reset}
${c0}     /  ${c1}__  \     ${lc}uptime:    ${ic}${uptime}${reset}
${c1}    /  (  )  \    ${lc}packages:  ${ic}${packages}${reset}
${c1}   / __|  |__\\\\   ${lc}shell:     ${ic}${shell}${reset}
${c1}  ///        \\\\\  ${lc}${envtype}:        ${ic}${WM}${reset}

EOF
