#! /bin/sh

# Autostarts
sxhkd &
picom & 
xsetroot -cursor_name left_ptr &
polybar bar1 &
alacritty -e nvim &
chromium &
yandex-music &
steam &
alacritty & 
telegram-desktop & 
xrandr --output DP-0 --mode 1920x1080 --rate 165 &
nitrogen --restore &
bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         1
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config active_border_color #1a1b26
bspc config active_border_color #1a1b26
bspc config focus_follows_pointer true

# Desktop 1
bspc rule -a chromium  desktop='^1' follow=on focus=on;
bspc rule -a alacritty desktop='^1' follow=on focus=on;
bspc rule -a TelegramDesktop desktop='^1' follow=on focus=on;

# Desktop 2
bspc rule -a nvim  desktop='^2' follow=on focus=on;

# Desktop 3
bspc rule -a yandex-music desktop='^3' follow=on focus=on;

# Desktop 4
bspc rule -a steam desktop='^4' follow=on focus=on;

