#! /bin/sh

# Autostarts
sxhkd &
picom -b --config ~/.config/picom/picom.conf& 
polybar bar1 &
# telegram-desktop & 
spoofdpi --enable-doh --window-size 0 &
chromium  --proxy-server="http://127.0.0.1:8080" &
yandex-music &
# alacritty & 
xrandr --output DP-0 --mode 1920x1080 --rate 165 &
nitrogen --random --set-auto &
bspc monitor -d 1 2 3 4 5 6 


bspc config border_width         3
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
#

bspc config normal_border_color "#1A1B26"         # Рамки неактивных окон - сливаются с фоном
bspc config active_border_color "##7899FA"         # Рамки активных окон - чуть светлее для легкого акцента
bspc config focused_border_color "#7899FA"        # Рамки выбранных окон - яркий синий для выделения
bspc config presel_feedback_color "#BB9AF7"       # Цвет предпросмотра - нежный фиолетовый, подчёркивающий стиль
bspc config focus_follows_pointer true


# Desktop 1
bspc rule -a chromium  desktop='^1' follow=on focus=on;
# bspc rule -a TelegramDesktop desktop='^1' follow=off focus=on;


bspc rule -a Alacritty state=floating center=on rectangle=620x420+0+0;
bspc rule -a Gpicview state=floating center=on rectangle=960x540+0+0;

# Desktop 3
bspc rule -a YandexMusic desktop='^3' focus=off follow=off state=floating center=on locked=on;

bspc rule -a Minecraft* 1.21.1 follow=on focus=on state=fullscreen;

